<?php
declare(strict_types=1);

return [
    'hero' => [
        'eyebrow' => 'Graduate software engineer',
        'name' => 'Jake Andrews',
        'title' => 'First Class Honours Computer Science Graduate',
        'tagline' => 'I build secure backend systems, REST APIs, and full-stack applications across Python, TypeScript, PHP, Java, and cloud-ready infrastructure.',
        'cta_text' => 'View Projects',
        'cta_target' => '#projects',
    ],
    'facts' => [
        'Degree' => 'BSc (Hons) Computer Science - First Class Honours',
        'University' => 'University of Salford',
        'Interests' => 'Backend Engineering | Full-Stack Development | Cloud Technologies | Secure Software | APIs',
        'Personal interests' => 'Technology | Gym | Music | Film & Media',
    ],
    'about' => [
        'heading' => 'Backend-focused graduate developer',
        'body' => [
            'First Class Honours Computer Science graduate from the University of Salford with experience developing secure backend systems, REST APIs, and full-stack applications.',
            'I am especially interested in backend engineering, cloud technologies, secure software, and modern architecture. My recent work includes a security-focused password vault implementing OWASP-aligned controls and a cloud-native retail intelligence platform using TypeScript, React, NestJS, Docker, and PostgreSQL.',
        ],
    ],
    'skills' => [
        'Python',
        'TypeScript',
        'JavaScript',
        'Java',
        'PHP',
        'SQL',
        'React',
        'NestJS',
        'FastAPI',
        'Symfony',
        'PostgreSQL',
        'Docker',
        'GitHub Actions',
        'AWS',
        'Linux',
        'Argon2id',
        'AES-GCM',
        'JWT',
        'MFA',
        'OWASP ZAP',
    ],
    'skill_categories' => [
        'Languages' => ['Python', 'TypeScript', 'JavaScript', 'Java', 'PHP', 'SQL', 'HTML', 'CSS'],
        'Frameworks & Libraries' => ['React', 'NestJS', 'FastAPI', 'Django', 'Flask', 'Symfony', 'Bootstrap'],
        'Databases' => ['PostgreSQL', 'MySQL', 'SQLite'],
        'Cloud & Infrastructure' => ['Docker', 'Docker Compose', 'GitHub Actions', 'AWS', 'Linux', 'WSL', 'CI/CD'],
        'Security' => ['Argon2id', 'AES-GCM', 'JWT', 'MFA', 'OWASP ZAP', 'Secure Cookies', 'CSRF Protection'],
        'Development Tools' => ['Git', 'GitHub', 'Postman', 'Wireshark', 'Pytest', 'VS Code', 'IntelliJ'],
    ],
    'projects' => [
        [
            'name' => 'YourVault - Secure Secret Manager',
            'description' => 'Final year secure password manager built with FastAPI and PostgreSQL, including Argon2id hashing, AES-GCM encryption, TOTP MFA, breached-password checks, CSRF protection, secure cookies, account lockout, pytest, and OWASP ZAP validation aligned with OWASP and NIST recommendations.',
            'tech' => ['FastAPI', 'PostgreSQL', 'Argon2id', 'AES-GCM', 'OWASP ZAP'],
            'github' => 'https://github.com/Jake-Andrews-git/Your-Vault',
            'demo' => '',
            'image' => '/images/projects/yourvault-password-health.png',
            'image_alt' => 'YourVault password health dashboard showing analysed, compromised, reused, and similar password status metrics.',
        ],
        [
            'name' => 'PriceWatch - Retail Intelligence Platform',
            'description' => 'Collaborative cloud-native retail intelligence platform for monitoring product prices and historical trends across retailers, built in a two-person team with React, NestJS, PostgreSQL, Redis, RabbitMQ, Docker, GitHub pull requests, CI/CD, and an AWS-ready event-driven architecture.',
            'tech' => ['TypeScript', 'React', 'NestJS', 'RabbitMQ', 'Docker'],
            'github' => '',
            'demo' => '',
        ],
        [
            'name' => 'Tako Chart - Repository Analytics Platform',
            'description' => 'Client-led full-stack application developed for Red Ocelot Ltd, Competa b.v. and Bureau Veritas Group to analyse and compare Git repositories. Working as the team\'s designated backend developer, I expanded into a full-stack role and developed FastAPI endpoints, GitHub API integration, PostgreSQL queries and repository metadata processing alongside JavaScript functionality for interactive Plotly charts, repository comparison controls, dynamic contributor tables and UI updates.',
            'tech' => [
                'JavaScript',
                'Plotly.js',
                'FastAPI',
                'PostgreSQL',
                'GitHub API',
                'HTML',
                'CSS',
                'Scrum',
            ],
            'github' => 'https://github.com/G12-hc/tako-chart',
            'demo' => '',
        ],
        [
            'name' => 'Symfony Music Review API',
            'description' => 'RESTful Symfony API with JWT authentication, structured error handling, OpenAPI documentation, request validation, hierarchical access control, and Last.fm, MusicBrainz, and Cover Art Archive integrations.',
            'tech' => ['Symfony', 'JWT', 'OpenAPI', 'Doctrine', 'REST API'],
            'github' => 'https://github.com/Jake-Andrews-git/AWDAssignment1',
            'demo' => '',
            'image' => '/images/projects/music-reviews-admin-dashboard.png',
            'image_alt' => 'Symfony Music Reviews admin dashboard showing role hierarchy and permissions.',
        ],
        [
            'name' => 'Visual Information Analysis',
            'description' => 'Python image-processing work for vehicle segmentation, enhancement, and reconstruction, evaluated with SSIM, PSNR, entropy, and MSE quality metrics.',
            'tech' => ['Python', 'OpenCV', 'SSIM', 'PSNR', 'MSE'],
            'github' => 'https://github.com/Jake-Andrews-git/VIA_Assignment1',
            'demo' => '',
            'image' => '/images/projects/via-vehicle-warp-validation.png',
            'image_alt' => 'Vehicle image analysis output showing source body, destination body, warped body, edge alignment, validation metrics, and feature matches.',
        ],
        [
            'name' => 'Portfolio Website',
            'description' => 'Custom PHP portfolio deployed to Vercel with structured content data, Vercel Analytics, and a database-free contact flow.',
            'tech' => ['PHP', 'Bootstrap', 'Vercel', 'Analytics'],
            'github' => 'https://github.com/Jake-Andrews-git/Portfolio',
            'demo' => 'https://portfolio-kappa-ten-whvzlseqzx.vercel.app',
        ],
    ],
    'case_studies' => [
        [
            'name' => 'YourVault - Secure Secret Manager',
            'summary' => 'Designed and developed a secure password manager as a final year project.',
            'problem' => 'A password manager must protect credentials against database compromise, weak master passwords, brute force attacks, session hijacking, and unsafe recovery flows.',
            'approach' => 'Implemented FastAPI services backed by PostgreSQL with Argon2id password hashing, AES-GCM encryption, TOTP multi-factor authentication, CSRF protection, secure cookies, account lockout, password health analysis, and Have I Been Pwned breach detection.',
            'outcome' => 'Validated the system with pytest and OWASP ZAP while demonstrating secure backend architecture, applied cryptography, MFA design, and OWASP-aligned controls.',
            'tech' => ['FastAPI', 'PostgreSQL', 'Argon2id', 'AES-GCM', 'OWASP ZAP'],
            'github' => 'https://github.com/Jake-Andrews-git/Your-Vault',
            'image' => '/images/projects/yourvault-password-health.png',
            'image_alt' => 'YourVault password health dashboard showing password status metrics.',
        ],
        [
            'name' => 'PriceWatch - Retail Intelligence Platform',
            'summary' => 'Developing a collaborative full-stack platform for monitoring retailer prices and historical trends.',
            'problem' => 'Retail price monitoring needs reliable product tracking, historical trend storage, asynchronous processing, and a scalable deployment path.',
            'approach' => 'Building a TypeScript architecture with React, NestJS, PostgreSQL, Redis, RabbitMQ, Docker, GitHub issue tracking, pull requests, CI/CD workflows, and AWS-oriented deployment planning.',
            'outcome' => 'The project demonstrates modern full-stack development, collaborative delivery, containerised infrastructure, and event-driven backend design.',
            'tech' => ['TypeScript', 'React', 'NestJS', 'RabbitMQ', 'Docker'],
        ],
        [
            'name' => 'Tako Chart - Repository Analytics Platform',
            'summary' => 'Worked as the designated backend developer and expanded into full-stack development within a client-led repository analytics and visualisation team.',
            'problem' => 'The clients needed a clearer way to explore repository activity, compare codebases and understand metrics such as contributor activity, commit history, file sizes and functional lines of code.',
            'approach' => 'Working in an Agile Scrum team as the designated backend developer, I developed FastAPI endpoints, GitHub API data retrieval, PostgreSQL queries, repository metadata processing and line-count analysis. I expanded across the full stack by developing JavaScript functionality for repository selection, global chart switching, Plotly pie, bar and histogram visualisations, dynamic contributor ranking tables and interface updates.',
            'outcome' => 'The project delivered an interactive repository comparison interface and gave me practical experience contributing across a full-stack application, integrating external APIs, visualising data and adapting work through iterative stakeholder feedback.',
            'tech' => [
                'JavaScript',
                'Plotly.js',
                'FastAPI',
                'PostgreSQL',
                'GitHub API',
                'Agile Scrum',
            ],
            'github' => 'https://github.com/G12-hc/tako-chart',
        ],
        [
            'name' => 'Symfony Music Review API',
            'summary' => 'Built a structured PHP API for album reviews, metadata enrichment, and access-controlled operations.',
            'problem' => 'The application needed authenticated review workflows, external music metadata, documented API behaviour, validation, and role-aware permissions.',
            'approach' => 'Used Symfony, Doctrine, JWT authentication, OpenAPI documentation, structured exception handling, request validation, hierarchical access control, and integrations with Last.fm, MusicBrainz, and Cover Art Archive.',
            'outcome' => 'The project demonstrates framework-led PHP development, REST API design, authentication, third-party integrations, and maintainable service boundaries.',
            'tech' => ['Symfony', 'Doctrine', 'JWT', 'OpenAPI', 'PHP'],
            'github' => 'https://github.com/Jake-Andrews-git/AWDAssignment1',
            'image' => '/images/projects/music-reviews-admin-dashboard.png',
            'image_alt' => 'Symfony Music Reviews admin dashboard showing role hierarchy and permissions.',
        ],
        [
            'name' => 'Visual Information Analysis',
            'summary' => 'Developed Python image-processing pipelines for vehicle segmentation, enhancement, and reconstruction.',
            'problem' => 'Vehicle image analysis requires repeatable enhancement, segmentation, reconstruction, and objective quality evaluation.',
            'approach' => 'Built processing flows around enhancement, segmentation, split-and-merge reconstruction, and evaluation with SSIM, PSNR, entropy, and MSE metrics.',
            'outcome' => 'The project shows applied computer vision, measurement-driven evaluation, and algorithmic experimentation with Python image-processing tools.',
            'tech' => ['Python', 'OpenCV', 'Image Processing', 'Metrics'],
            'github' => 'https://github.com/Jake-Andrews-git/VIA_Assignment1',
            'image' => '/images/projects/via-vehicle-warp-validation.png',
            'image_alt' => 'Vehicle image analysis validation panel with warped vehicle output and metrics.',
        ],
    ],
    'experience' => [
        [
            'role' => 'Shop Assistant',
            'company' => 'Parfetts / Go Local',
            'dates' => 'Oct 2020 - Present',
            'details' => [
                'Delivered excellent customer service in a fast-paced retail environment.',
                'Developed communication, teamwork, and problem-solving skills.',
                'Managed stock replenishment and supported day-to-day store operations.',
            ],
        ],
    ],
    'education' => [
        [
            'institution' => 'University of Salford',
            'award' => 'BSc (Hons) Computer Science - First Class Honours',
            'dates' => 'Sep 2023 - Jul 2026',
        ],
        [
            'institution' => 'Clarendon Sixth Form',
            'award' => 'A Levels: Mathematics, Computer Science, Physics',
            'dates' => '2020 - 2022',
        ],
    ],
];
